client_config_backend: file
client_config_file: client_secrets.json
save_credentials: true
save_credentials_backend: file
save_credentials_file: pydrive2_credentials.json
get_refresh_token: true
oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.readonly
  - https://www.googleapis.com/auth/drive.metadata.readonly
